---
# Source: hello-rings-master/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rings-master
  labels:
    app.kubernetes.io/name: hello-rings-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-rings-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-rings-master
    spec:
      containers:
        - name: hello-rings-master
          image: "hellorings.azurecr.io/hellorings:hello-rings-master-3934"
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8080

---
# Source: hello-rings-master/templates/ring.yaml
# Source: hello-ring/templates/ring.yaml
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: master
spec:
  # Deploy to environment
  deploy: true
  # Custom Claims
  claim: production
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  match: PPathPrefix(`/`) && Headers(`x-ring`, `production`)
  selector:
    app.kubernetes.io/name: hello-rings-master

